api-key: ${API_KEY}

denominations:
    BGN: 5,10,20,50,100
    EUR: 5,10,20,50,100,200,500
spring:
    application:
        name: cash-desk
    config:
        import: file:./env.properties


cashdesk:
    cash:
        balances:
            file: src/main/resources/cash_balances.txt
        operations:
            file: src/main/resources/cash_operations.txt


